language: python
python: 2.7
env:
  - TOX_ENV=py27-1.8.X
  - TOX_ENV=py27-1.7.X
  - TOX_ENV=py27-1.6.X
  - TOX_ENV=py27-1.5.X
  - TOX_ENV=py27-1.4.X
  - TOX_ENV=docs
  - TOX_ENV=flake8
install:
  - pip install tox
script:
  - tox -e $TOX_ENV
